// ─── Insights Feature — Public API ────────────────────────────────────────────

export { computeTriggerFrequency, computeMonthlyStats } from './services/insightsService'
export { applyOutlierFilter } from './services/outlierFilter'
export { computeCorrelation } from './services/correlationEngine'
export { computeConfidence } from './services/confidenceModel'
export { computePrediction } from './services/predictionEngine'
export { formatNotificationPayload } from './services/notificationService'
export { useDashboardInsights } from './hooks/useDashboardInsights'
export { usePrediction } from './hooks/usePrediction'
export { useInsightsPage } from './hooks/useInsightsPage'
export { useInsightsStore } from './store/insightsStore'
export { default as PressureHeadacheChart } from './components/PressureHeadacheChart'
export { default as TriggerFrequencyBars } from './components/TriggerFrequencyBars'
export { default as MonthlyStatsBadge } from './components/MonthlyStatsBadge'
export { default as ConfidenceBar } from './components/ConfidenceBar'
export { default as PredictionCard } from './components/PredictionCard'
export { default as AnalysisWindowPicker } from './components/AnalysisWindowPicker'
export { default as CorrelationSummary } from './components/CorrelationSummary'
export { default as DashboardRiskRow } from './components/DashboardRiskRow'
export type { TriggerCount, MonthlyStats } from './services/insightsService'
